name: proypet
description: Reserva citas en segundos en Veterinarias Certificadas y accede a beneficios.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter    
  flutter_localizations:
    sdk: flutter
  google_maps_flutter: ^0.5.24+1
  geolocator: ^5.2.0

  geocoder: ^0.2.1
  # flutter_google_places: ^0.2.5
  # google_maps_webservice: ^0.0.16
  # flutter_google_places: ^0.2.5
  # location: ^1.4.1
  
  intl: ^0.16.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_messaging: ^6.0.15
  
  flutter_local_notifications: ^1.4.3

  dropdown_search: ^0.4.2

  simple_autocomplete_formfield: ^0.2.7

  google_maps_webservice: ^0.0.16
  
  # search_map_place: ^0.3.0

  # google_place: ^0.3.1
  # autocomplete_textfield: ^1.7.3
  # flutter_places_autocomplete: ^0.2.0

  animate_do: ^1.6.3
  cached_network_image: ^2.0.0
  datetime_picker_formfield: ^1.0.0
  flutter_rating_bar: ^3.0.1+1
  flutter_swiper: ^1.1.6
  font_awesome_flutter: ^8.8.0  
  http:
  image_cropper: ^1.2.1  
  image_picker:
  map_launcher: ^0.4.5
  mime_type:
  rxdart: ^0.23.1
  searchable_dropdown: ^1.1.3  
  share: ^0.6.3+6
  shared_preferences:    
  url_launcher: ^5.4.5
  # google_fonts: ^1.0.0
  # line_awesome_icons: ^1.0.4+2
  # decimal: ^0.3.5
  # number_display: 
  # image_crop: ^0.3.2
  # simple_image_crop: ^0.1.3
  # flutter_image_compress: ^0.6.5+1
  # flutter_responsive: ^0.0.6  
  # smooth_star_rating: ^1.0.4+2
  # condition: ^0.0.7
  # animations: ^1.0.0+5
  # shimmer: ^1.1.1
  # webview_flutter: ^0.3.20+2
  

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_launcher_icons:
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon/proypet-c.png"
  adaptive_icon_background: "images/icon/proypet-c.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/map_style.txt
   - images/
  #  - images/greco.png
  #  - images/vet_prueba.jpg
  #  - images/veterinaria.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Proypet
      fonts:
        - asset: fonts/Proypet.ttf
        # - asset: fonts/Schyler-Italic.ttf
        #   style: italic
    - family: IconProypet
      fonts:
        - asset: fonts/IconProypet.ttf
    - family: Lato
      fonts:
        - asset: fonts/Lato/Lato-Regular.ttf
        - asset: fonts/Lato/Lato-Bold.ttf
          weight: 700
    # - family: PT Sans
    #   fonts:
    #     - asset: fonts/PT_Sans/PTSans-Regular.ttf
    #     - asset: fonts/PT_Sans/PTSans-Bold.ttf
    #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
