name: proypet
description: Reserva citas en segundos en Veterinarias Certificadas y accede a beneficios.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter    
  flutter_localizations:
    sdk: flutter
  
  cron: ^0.2.4
  path_provider:
  sqflite:

  ai_notification_enable: ^1.6.0
  animate_do: ^1.6.3
  badges: ^1.1.4  
  cached_network_image: ^2.0.0
  datetime_picker_formfield: ^1.0.0
  dotted_line: ^2.0.2
  dio: ^3.0.10
  dio_http_cache: ^0.2.8
  email_validator: ^1.0.6
  firebase_messaging: ^6.0.15
  flutter_conditional_rendering: ^1.1.1
  flutter_email_sender: ^3.0.1
  flutter_local_notifications: ^3.0.2
  flutter_login_facebook: ^0.4.1 #login con facebook
  flutter_rating_bar: ^3.0.1+1
  flutter_svg_provider: ^0.1.8
  flutter_swiper: ^1.1.6
  font_awesome_flutter: ^8.8.0  
  geolocator: ^5.2.0
  geocoder: ^0.2.1
  get:
  get_storage:
  google_fonts: ^1.1.1
  google_maps_flutter: ^0.5.28+1
  google_maps_webservice: ^0.0.16
  # google_sign_in: ^4.5.6 #login con google
  google_sign_in: ^4.5.9 #login con google
  http:
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+21
  intl: ^0.16.1 #para formatos
  lottie: ^0.7.0+1
  map_launcher: ^0.4.5
  mime_type:
  overflow_view:
  rxdart: ^0.23.1
  scrollable_positioned_list: ^0.1.8
  select_dialog: ^1.2.1
  share: ^0.6.4+3
  simple_autocomplete_formfield: ^0.2.7 #buscar con autocomplete 
  time_parser: ^1.1.0
  url_launcher: ^5.5.0
  
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:   

  # sign_button: ^1.0.1
  # flutter_onboard: ^0.1.0
  # dots_indicator: 1.2.0
  # minimal_onboarding: ^1.0.0
  # on_boarding_ui: ^0.0.4
  # onboarding: ^1.0.5
  # onboardme: ^1.2.0
  # some_calendar: ^1.2.6 #nuevo calendar
  # cupertino_stepper: ^0.1.2
  # image_sequence_animator: ^1.0.9
  # flutter_typeahead_web: ^1.0.0+1
  # spritewidget: ^0.9.24
  # flame: ^0.28.0
  # flim: ^0.3.1
  # featurestar: ^1.1.0
  # flutter_rating_bar: ^3.2.0+1
  # native_updater: ^0.0.3
  # package_info: ^0.4.3+2
  # nuevos
  # launchers: ^0.4.6
  # whatsapp_unilink: ^1.0.0+1
  # flutter_web_browser: ^0.13.0
  # progressive_image: ^1.0.1
  # image_crop: ^0.3.4
  # crop: ^0.4.1
  # # simple_image_crop: ^1.0.0 #invalido
  # images_picker: ^0.0.5
  # image_picker_gallery_camera: ^0.1.6
  # image_pickers: ^1.0.8+7
  #
  # infinite_scroll_pagination: ^2.2.2
  # websafe_network_image: ^1.0.5
  # flutter_login_facebook: ^0.3.0
  # shared_preferences: ^0.5.12+2
  # select_dialog: ^1.1.0 
  # flutter_local_notifications: ^1.4.3
  # get_it:
  # textfield_search: ^0.6.1
  # flutter_snake_navigationbar: ^0.4.0+1
  # searchable_dropdown: ^1.1.3
  # shared_preferences: ^0.5.7+3
  # provider: ^4.3.1 #mobx +
  # flutter_mobx: ^1.1.0+1 #mobx 
  # mobx: ^1.2.1+1 #mobx

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon/proypet-c.png"
  adaptive_icon_background: "images/icon/proypet-c.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/map_style.txt
   - images/
   - images/gif/
   - images/icon/
   - images/lottie/
   - images/notificacion/
   - images/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Proypet
      fonts:
        - asset: assets/fonts/Proypet.ttf
        # - asset: fonts/Schyler-Italic.ttf
        #   style: italic
    - family: IconProypet
      fonts:
        - asset: assets/fonts/IconProypet.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
    # - family: PT Sans
    #   fonts:
    #     - asset: fonts/PT_Sans/PTSans-Regular.ttf
    #     - asset: fonts/PT_Sans/PTSans-Bold.ttf
    #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages